language: cpp

os: linux
dist: xenial
compiler: gcc
addons:
  apt:
    packages:
      - cmake
      - zlib1g-dev
      - libjpeg-turbo8-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libfreetype6-dev
      - libopenal-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libogg-dev
      - libopus-dev
      - libpng12-dev
      - libspeex-dev
      - uuid-dev
      - libvpx-dev
      - libvorbis-dev
      - libsecret-1-dev
      - python2.7-dev
      - qtbase5-dev

script:
  - mkdir -p build_deps && cd build_deps
  - git clone https://github.com/zrax/string_theory
  - mkdir -p string_theory/build && cd string_theory/build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DST_BUILD_TESTS=OFF
      -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/build_deps/prefix" ..
  - make -j2 && make install

  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="${TRAVIS_BUILD_DIR}/build_deps/prefix"
      -DPython_ADDITIONAL_VERSIONS=2.7 -DPLASMA_BUILD_TESTS=ON
      -DPLASMA_BUILD_TOOLS=ON -DPLASMA_BUILD_RESOURCE_DAT=ON ${CMAKE_EXTRA_ARGS} ..
  - make -j2
