//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Fc ps_RiftDistortAssembly.inl /E main /T ps_3_0
//    ps_RiftDistortAssembly.fx
//
//
// Parameters:
//
//   float4 HmdWarpParam;
//   float2 LensCenter;
//   Texture2D Linear+Texture;
//   float2 Scale;
//   float2 ScaleIn;
//   float2 ScreenCenter;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   LensCenter     c0       1
//   ScreenCenter   c1       1
//   Scale          c2       1
//   ScaleIn        c3       1
//   HmdWarpParam   c4       1
//   Linear+Texture s1       1
//

    ps_3_0
    def c5, -0.25, -0.5, 0.25, 0.5
    def c6, 0, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s1
    add r0.xy, -c0, v0
    mul r0.xy, r0, c3
    dp2add r0.z, r0, r0, c6.x
    mad r0.w, c4.y, r0.z, c4.x
    mul r1.x, r0.z, r0.z
    mad r0.w, r1.x, c4.z, r0.w
    mul r1.x, r1.x, c4.w
    mad r0.z, r1.x, r0.z, r0.w
    mul r0.xy, r0.z, r0
    mov r1.xy, c0
    mad r0.xy, c2, r0, r1
    mov r1.xy, c1
    add r1, r1.xyxy, c5
    max r2.xy, r0, r1
    min r0.zw, r1, r2.xyxy
    add r0.zw, -r0.xyxy, r0
    texld r1, r0, s1
    dp2add r0.x, r0.zwzw, r0.zwzw, c6.x
    cmp oC0, -r0.x, r1, c6.x

// approximately 21 instruction slots used (1 texture, 20 arithmetic)
