//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc -T ps_2_0 -Fc ps_RiftDistortAssembly.inl ps_RiftDistort.inl
//
//
// Parameters:
//
//   float4 HmdWarpParam;
//   float2 LensCenter;
//   Texture2D Linear+Texture;
//   float2 Scale;
//   float2 ScaleIn;
//   float2 ScreenCenter;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   LensCenter     c0       1
//   ScreenCenter   c1       1
//   Scale          c2       1
//   ScaleIn        c3       1
//   HmdWarpParam   c4       1
//   Linear+Texture s1       1
//

    ps_2_0
    def c5, -0.25, -0.5, 0.5, 0.25
    def c6, 0, 0, 0, 0
    dcl t0.xy
    dcl_2d s1
    add r0.xy, t0, -c0
    mul r0.xy, r0, c3
    mul r0.z, r0.y, r0.y
    mad r0.z, r0.x, r0.x, r0.z
    mad r0.w, c4.y, r0.z, c4.x
    mul r1.w, r0.z, r0.z
    mad r0.w, r1.w, c4.z, r0.w
    mul r1.x, r1.w, c4.w
    mad r0.z, r1.x, r0.z, r0.w
    mul r0.xy, r0.z, r0
    mov r1.xy, c0
    mad r0.xy, c2, r0, r1
    mov r1.xy, c1
    add r0.zw, r1.wzyx, c5.wzyx
    max r1.zw, r0.wzyx, r0
    add r0.zw, r1.wzyx, c5
    min r2.xy, r0.wzyx, r1.wzyx
    add r1.xy, -r0, r2
    texld r0, r0, s1
    dp2add r1.x, r1, r1, c6.x
    cmp r0, -r1.x, r0, c6.x
    mov oC0, r0

// approximately 23 instruction slots used (1 texture, 22 arithmetic)
