//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /Fc vs_RiftDistortAssembly.inl /E vs_main /T vs_3_0
//    vs_RiftDistortAssembly.fx
//
//
// Parameters:
//
//   float4x4 Texm;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Texm         c4       4
//

    vs_3_0
    def c0, 1, 0, 0, 0
    dcl_position v0
    dcl_color v1
    dcl_texcoord v2
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2.xy
    mov o0, v0
    mov o1, v1
    mul r0.xy, c5, v2.y
    mad r0.xy, c4, v2.x, r0
    add r0.xy, r0, c7
    add r0.z, -r0.y, c0.x
    mov o2.xy, r0.xzzw

// approximately 7 instruction slots used
