//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc -Fc vs_RiftDistortAssembly.inl vs_RiftDistort.inl
//
//
// Parameters:
//
//   float4x4 Texm;
//   float4x4 View;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   View         c4       4
//   Texm         c8       4
//

    vs_2_0
    dcl_position v0
    dcl_color v1
    dcl_texcoord v2
    mul r0, v0.y, c5
    mad r0, c4, v0.x, r0
    mad r0, c6, v0.z, r0
    mad oPos, c7, v0.w, r0
    mul r0.xy, v2.y, c9
    mad r0.xy, c8, v2.x, r0
    add oT0.xy, r0, c11
    mov oD0, v1

// approximately 8 instruction slots used
